---
homeassistant:
  name: Hjem
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Oslo
  packages: !include_dir_named components/packages
  whitelist_external_dirs:
    - /home/homeassistant/.homeassistant/

hacs:
  token: !secret hacs_token
  python_script: true
  theme: true
