---
# Loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Assistant
resources: !include_dir_list lovelace/resources
views:
  - !include lovelace/views/default_view.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/tablet.yaml
  - !include lovelace/views/system.yaml
