select_picture_mode:
  description: Send the samsung TV the command to change picture mode.
  fields:
    entity_id:
      description: Name of the target entity
      example: "media_player.tv"
    picture_mode:
      description: >
        Name of the picture mode to switch to. Possible options can be found in the
        picture_mode_list state attribute.
      example: "Standard"

set_art_mode:
  description: Send the samsung TV the command to set art mode.
  fields:
    entity_id:
      description: Name of the target entity
      example: "media_player.tv"
