---
alias: status_sonos_office_playing
trigger:
  - platform: state
    entity_id: sensor.mediastatus_sonos_office
    to: 'Spiller'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.media_sonos_office
