# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/scenes.html

scenes:
  - entity: scene.kontor_media_playing
    icon: fas:couch
    icon_color: '#ffffff'
    background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'
