---
homeassistant:

  # Customize individual entities
  customize: !include_dir_merge_named ../../customizations/entities

  # Custimize all entities by domain
  # customize_domain: !include_dir_merge_named ../../customizations/domains

  # Custimize entities based on a pattern
  # customize_glob: !include_dir_merge_named ../../customizations/globs
