---
alias: keyfob_square_short
initial_state: true
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_keyfob
      scene_id: 1
      scene_data: 7680
action:
  - service: homeassistant.toggle
    data:
      entity_id:
        - fan.bedroom
