---
alias: keyfob_circle_short
initial_state: true
hide_entity: false
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_keyfob
      scene_id: 2
      scene_data: 7680
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.soverom
