---
alias: keyfob_x_long
initial_state: true
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_keyfob
      scene_id: 2
      scene_data: 7740
action:
  - service: media_player.media_pause
    data:
      entity_id:
        - media_player.soverom
