---
alias: keyfob_x_short
initial_state: true
hide_entity: false
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_keyfob
      scene_id: 2
      scene_data: 7680
action:
  - service: media_player.volume_set
    data_template:
      entity_id:
        - media_player.soverom
      volume_level: 0.2
