---
alias: keyfob_circle_long
initial_state: true
hide_entity: false
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_keyfob
      scene_id: 2
      scene_data: 7740
action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - fan.office
