---
alias: Minimote 1 Button 1 Short Press
initial_state: true
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeotec_minimote
      scene_id: 1
action:
  service: switch.toggle
  data:
    entity_id:
      - switch.sonoff_pow_06
      - switch.livingroom_moodlight_1_switch
      - switch.livingroom_moodlight_2_switch
