---
alias: Minimote 1 Button 4 Short Press
initial_state: true
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeotec_minimote
      scene_id: 7

action:
  - service: homassistant.turn_off
    data:
      entity_id:
        - group.indoor_lights

  - service: switch.turn_off
    entity_id:
      - switch.sonoff_pow_06
      - switch.livingroom_moodlight_1_switch
      - switch.livingroom_moodlight_2_switch
