---
alias: home_office_enable
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: ENABLE_INPUTBOOL
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.home_office
  - service: notify.discord_text
    data_template:
      message: ":man_office_worker: Hjemmekontormodus på."
