---
alias: home_mode_set_day
initial_state: true
trigger:
  - platform: time
    at: '07:00:00'
action:
  service: input_select.select_option
  data:
    entity_id: input_select.home_mode
    option: Dag
