---
alias: ifttt
initial_state: true
trigger:
  platform: event
  event_type: ifttt_webhook_received
  event_data:
    action: call_service
action:
  - data:
      entity_id: "{{ trigger.event.data.entity_id }}"
    service: "{{ trigger.event.data.service }}"
