---
alias: zwave_complete
initial_state: true
trigger:
  platform: event
  event_type: zwave.network_complete
action:
  - service: notify.discord_text
    data_template:
      message: "Z-Wave network is complete"
  - service: notify.mobile_app_person1_sin_iphone_11_pro
    data_template:
      message: "Z-Wave network is complete"
