---
alias: zwave_starting
initial_state: true
trigger:
  platform: event
  event_type: zwave.network_start
action:
  - service: notify.discord_text
    data_template:
      message: "Z-Wave network is starting..."
  - service: notify.mobile_app_person1_sin_iphone_11_pro
    data_template:
      message: "Z-Wave network is starting..."
