---
alias: bedroom_bed_light_off
trigger:
  - platform: state
    entity_id: light.taklampe_1, light.taklampe_2, light.taklampe_3
    to: 'off'

action:
  - service: light.turn_off
    entity_id:
      - light.bedroom_bed_led
    data:
      transition: 2
