---
alias: bedroom_light_off
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_multisensor_home_security_motion_detected
    to: "off"
    for: "00:10:00"

action:
  - service: light.turn_off
    entity_id:
      - light.bedroom_bed_led
      - light.bedroom
      - light.taklampe_1
      - light.taklampe_2
      - light.taklampe_3
      - light.nightstand_person1
    data:
      transition: 1
