---
alias: bedroom_bed_light_on
trigger:
  - platform: state
    entity_id: light.taklampe_1, light.taklampe_2, light.taklampe_3
    to: 'on'

action:
  - service: light.turn_on
    entity_id:
      - light.bedroom_bed_led
    data:
      transition: 1
