---
alias: office_media_paused
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.sjabbyrogw8
    to: 'paused'
action:
  - service: light.turn_on
    data_template:
      entity_id:
        - light.hue_iris_1
      rgb_color: [255, 31, 50]
      brightness_pct: 80
      transition: 1
  - service: light.turn_on
    data_template:
      entity_id:
        - light.hue_iris_2
      rgb_color: [19, 96, 255]
      brightness_pct: 80
      transition: 1
