---
alias: office_media_playing
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.plex_sjabby_rogw8
    to: 'playing'
action:
  - service: switch.turn_off
    data_template:
      entity_id: switch.flux_office

  - service: light.turn_on
    data_template:
      entity_id:
        - light.hue_iris_1
        - light.hue_iris_2
      rgb_color: [142, 153, 150]
      brightness_pct: 50
      transition: 1

  - service: light.turn_on
    data_template:
      entity_id:
        - light.kontoret_taklampe
      color_temp: 154
      brightness_pct: 30
      transition: 1
