---
alias: office_light_on
trigger:
  platform: state
  entity_id: binary_sensor.office_multisensor_sensor
  to: "on"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: "sensor.office_multisensor_illuminance"
      below: "50"
    - condition: state
      entity_id: light.kontoret
      state: "off"

action:
  service: light.turn_on
  data_template:
    entity_id:
      - light.kontoret_taklampe
      - light.hue_iris_1
      - light.hue_iris_2
    color_temp: >-
      {% if is_state("input_select.home_mode", "Dag") %}
      {{ states('input_number.home_mode_day_color_temp_value') | int }}
      {% elif is_state("input_select.home_mode", "Kveld") %}
      {{ states('input_number.home_mode_evening_color_temp_value') | int }}
      {% elif is_state("input_select.home_mode", "Natt") %}
      {{ states('input_number.home_mode_night_color_temp_value') | int }}
      {% else %}
        180
      {% endif %}
    brightness_pct: >-
      {% if is_state("input_select.home_mode", "Dag") %}
      {{ states('input_number.home_mode_day_brightness_value') | int }}
      {% elif is_state("input_select.home_mode", "Kveld") %}
      {{ states('input_number.home_mode_evening_brightness_value') | int }}
      {% elif is_state("input_select.home_mode", "Natt") %}
      {{ states('input_number.home_mode_night_brightness_value') | int }}
      {% else %}
        100
      {% endif %}
    transition: >-
      {% if is_state("input_select.home_mode", "Dag") %}
      {{ states('input_number.home_mode_day_transition_value') | int }}
      {% elif is_state("input_select.home_mode", "Kveld") %}
      {{ states('input_number.home_mode_evening_transition_value') | int }}
      {% elif is_state("input_select.home_mode", "Natt") %}
      {{ states('input_number.home_mode_night_transition_value') | int }}
      {% else %}
        1
      {% endif %}
