---
alias: office_light_off
trigger:
  platform: state
  entity_id: binary_sensor.office_multisensor_motion
  to: 'off'
  for: '00:10:00'

condition:
  - condition: template
    value_template: "{{ not is_state('sensor.steam_76561198015754950', 'online') }}"
  - condition: template
    value_template: "{{ not is_state('sensor.playingonsteam', 'game') }}"
  - condition: template
    value_template: "{{ not is_state('media_player.plex_sjabby_w10', 'playing') }}"
  - condition: state
    entity_id: input_boolean.home_office
    state: 'off'
action:
  service: light.turn_off
  data_template:
    entity_id:
      - light.kontoret_taklampe
      - light.hue_iris_1
      - light.hue_iris_2
    transition: >-
      {% if is_state("input_select.home_mode", "Dag") %}
      {{ states('input_number.home_mode_day_transition_value') | int }}
      {% elif is_state("input_select.home_mode", "Kveld") %}
      {{ states('input_number.home_mode_evening_transition_value') | int }}
      {% elif is_state("input_select.home_mode", "Natt") %}
      {{ states('input_number.home_mode_night_transition_value') | int }}
      {% else %}
        1
      {% endif %}
