---
alias: storage_light_on
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.storage_multisensor_motion
    to: "on"
action:
  service: switch.turn_on
  entity_id: switch.storage_ceiling_light
