---
alias: vacuum_finished
trigger:
  - platform: state
    entity_id: vacuum.rocky
    to: 'docked'
action:
  - service: notify.discord_text
    data_template:
      message: >-
        :robot: Ferdig! Rocky har støvsugd {{state_attr("vacuum.rocky", "cleaned_area")}} kvm
        på {{state_attr("vacuum.rocky", "cleaning_time")}} minutter!
