---
alias: vacuum_finished
trigger:
  - platform: state
    entity_id: sensor.xiaomi_vacuum_cleaner_status
    to: 'Charging'
action:
  # - service: notify.ios_person1s_iphonex
  #   data_template:
  #     message: >
  #       Ferdig! Rocky har støvsugd {{states.vacuum.rocky.attributes.cleaned_area}} kvm på
  #        {{states.vacuum.rocky.attributes.cleaning_time}} minutter!
  - service: notify.discord_text
    data_template:
      message: >-
        :robot: Ferdig! Rocky har støvsugd {{states.vacuum.rocky.attributes.cleaned_area}} kvm på
         {{states.vacuum.rocky.attributes.cleaning_time}} minutter!
